services:

  dbusers:
    image: mysql:8.0
    restart: always
    ports:
      - "1001:3306"
    environment:
      MYSQL_DATABASE: dbUsers
      MYSQL_ROOT_PASSWORD: dbusers123
    volumes:
      - ./DB/dbUsers/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  dbincomes:
    image: mysql:8.0
    restart: always
    ports:
      - "1002:3306"
    environment:
      MYSQL_DATABASE: dbIncomes
      MYSQL_ROOT_PASSWORD: dbincome123
    volumes:
      - ./DB/dbIncomes/init.sql:/docker-entrypoint-initdb.d/init.sql

  dbcosts:
    image: mysql:8.0
    restart: always
    ports:
      - "1003:3306"
    environment:
      MYSQL_DATABASE: dbCosts
      MYSQL_ROOT_PASSWORD: dbcost123
    volumes:
      - ./DB/dbCosts/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./BackEnd
    ports:
      - "8081:8081"
    depends_on:
      - dbusers
      - dbincomes
      - dbcosts

  frontend:
    build: ./FrontEnd
    ports:
      - "8080:8080"
    depends_on:
      - backend