# Use root/example as user/password credentials
version: '3.1'

services:

  db1:
    image: mysql
    restart: always
    ports:
      - 8082
    environment:
      MYSQL_ROOT_PASSWORD: example1
  
  db2:
    image: mysql
    restart: always
    ports:
      - 8083
    environment:
      MYSQL_ROOT_PASSWORD: example2
    
  db3:
    image: mysql
    restart: always
    ports:
      - 666
    environment:
      MYSQL_ROOT_PASSWORD: example3