services:

  dbUsers:
    image: mysql:8.0
    restart: always
    ports:
      - "1001:3306"
    environment:
      MYSQL_DATABASE: dbUsers
      MYSQL_ROOT_PASSWORD: dbusers123
    volumes:
      - ./dbUsers/init.sql:/docker-entrypoint-initdb.d/init.sql
      
  dbIncomes:
    image: mysql:8.0
    restart: always
    ports:
      - "1002:3307"
    environment:
      MYSQL_DATABASE: dbIncomes
      MYSQL_ROOT_PASSWORD: dbIncome123
    volumes:
      - ./dbIncomes/init.sql:/docker-entrypoint-initdb.d/init.sql

  dbCosts:
    image: mysql:8.0
    restart: always
    ports:
      - "1003:3308"
    environment:
      MYSQL_DATABASE: dbCosts
      MYSQL_ROOT_PASSWORD: dbCost123
    volumes:
      - ./dbCosts/init.sql:/docker-entrypoint-initdb.d/init.sql
